export const FEATURED_EXPERIENCES = [
  {
    createdAt: {
      date: '2024-07-06 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-06 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 1,
    title: 'Full Stack Developer',
    company: 'Ethika',
    summary:
      'Led the creation of a music content management system to manage talent, track assets, and provide analytics. Improved page load times by 30% by optimizing image storage and modernized our state management system. Integrated Klaviyo to handle email, SMS, and back-in-stock notifications, boosting customer engagement. Designed and launched a promotional video game that attracted 20,000 players and hit 550,000+ total plays, driving brand engagement in a fun, creative way. Integrated Algolia search into product pages, aligned a complex tagging system with Algolia’s payload structure, and added a custom debouncer to help reduce hits to Algolia, lowering costs. Developed a Wix-like system enabling the E-commerce team to create and manage media-rich pages.',
    url: 'https://www.ethika.com/',
    startDate: {
      date: '2022-05-25 23:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    endDate: null,
    visible: true,
    tags: [
      {
        createdAt: {
          date: '2024-07-13 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-13 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 3,
        title: 'Vue.js',
        logoName: 'vuedotjs',
        url: 'https://vuejs.org/guide/introduction.html',
        featured: true,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 4,
        title: 'PHP',
        logoName: 'php',
        url: 'https://www.php.net/manual/en',
        featured: true,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 10,
        title: 'MongoDB',
        logoName: 'mongodb',
        url: 'https://www.mongodb.com/docs',
        featured: true,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 19,
        title: 'Symfony',
        logoName: 'symfony',
        url: 'https://symfony.com/doc/current/index.html',
        featured: true,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 20,
        title: 'Bootstrap',
        logoName: 'bootstrap',
        url: 'https://getbootstrap.com/docs/5.3/getting-started/introduction',
        featured: true,
        experiences: {},
        projects: {},
      },
      {
        createdAt: null,
        modifiedAt: null,
        id: 48,
        title: 'AWS',
        logoName: null,
        url: null,
        featured: false,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 1,
        title: 'Typescript',
        logoName: 'typescript',
        url: 'https://www.typescriptlang.org/docs/',
        featured: true,
        experiences: {},
        projects: {},
      },
    ],
  },
  {
    createdAt: {
      date: '2025-09-02 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2025-09-02 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 5,
    title: 'Lead Developer / Owner',
    company: 'The Inked Network',
    summary:
      'I developed and launched a Nuxt + Supabase web app adopted by 200+ tattoo artists, featuring real-time chat, profile management, and subscription capabilities. I integrated Stripe, Google Maps, OpenAI GPT-4o, and ImageKit/S3 to enable subscriptions, AI-powered search, event management, and automated image tagging. To ensure security and scalability, I designed Supabase role-based access control and row-level security policies, isolating chat sessions and managing controlled file uploads.',
    url: 'https://www.theinkednetwork.com',
    startDate: {
      date: '2025-06-18 17:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    endDate: null,
    visible: true,
    tags: [],
  },
  {
    createdAt: {
      date: '2024-07-12 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-12 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 2,
    title: 'Programmer',
    company: 'Saddleback College Robotics',
    summary:
      'As part of the only community college team to reach the finals of the University Rover Challenge (URC), I developed a Django-based web GUI integrated with ROS2 to enable real-time rover navigation, science platform control, and system monitoring, boosting our performance by three ranks. Additionally, I created an onboarding program to train new members in autonomous driving, focusing on OpenCV, LIDAR sensors, and essential robotics concepts, fostering team growth and technical expertise.',
    url: 'https://www.youtube.com/watch?v=SAtsOZK6AJ4&ab_channel=SCRobotics',
    startDate: {
      date: '2023-07-25 17:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    endDate: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    visible: true,
    tags: [
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 13,
        title: 'Python',
        logoName: 'python',
        url: 'https://docs.python.org/3',
        featured: true,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 21,
        title: 'ROS2',
        logoName: null,
        url: 'https://docs.ros.org/en/humble/index.html',
        featured: false,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 22,
        title: 'NAV2',
        logoName: null,
        url: null,
        featured: false,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 23,
        title: 'odrive',
        logoName: null,
        url: null,
        featured: false,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 24,
        title: 'Robotics',
        logoName: null,
        url: null,
        featured: false,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 25,
        title: 'Autonomous Vehicles',
        logoName: null,
        url: null,
        featured: false,
        experiences: {},
        projects: {},
      },
      {
        createdAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        modifiedAt: {
          date: '2024-07-14 00:00:00.000000',
          timezone_type: 3,
          timezone: 'UTC',
        },
        id: 14,
        title: 'Linux',
        logoName: 'linux',
        url: 'https://github.com/torvalds/linux',
        featured: false,
        experiences: {},
        projects: {},
      },
    ],
  },
] as const;
