export const FEATURED_TAGS = [
  {
    createdAt: {
      date: '2024-07-13 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-13 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 3,
    title: 'Vue.js',
    logoName: 'vuedotjs',
    url: 'https://vuejs.org/guide/introduction.html',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 4,
    title: 'PHP',
    logoName: 'php',
    url: 'https://www.php.net/manual/en',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 5,
    title: 'C++',
    logoName: 'cplusplus',
    url: 'https://en.cppreference.com/w',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 6,
    title: 'Tailwind CSS',
    logoName: 'tailwindcss',
    url: 'https://tailwindcss.com/docs/installation',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 10,
    title: 'MongoDB',
    logoName: 'mongodb',
    url: 'https://www.mongodb.com/docs',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 13,
    title: 'Python',
    logoName: 'python',
    url: 'https://docs.python.org/3',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 19,
    title: 'Symfony',
    logoName: 'symfony',
    url: 'https://symfony.com/doc/current/index.html',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 20,
    title: 'Bootstrap',
    logoName: 'bootstrap',
    url: 'https://getbootstrap.com/docs/5.3/getting-started/introduction',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 1,
    title: 'Typescript',
    logoName: 'typescript',
    url: 'https://www.typescriptlang.org/docs/',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 50,
    title: 'Docker',
    logoName: 'docker',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 51,
    title: 'Nestjs',
    logoName: 'nestjs',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 52,
    title: 'Django',
    logoName: 'django',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 53,
    title: 'AWS',
    logoName: 'aws',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 54,
    title: 'Postgresql',
    logoName: 'postgresql',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 55,
    title: 'Redis',
    logoName: 'redis',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 56,
    title: 'Supabase',
    logoName: 'supabase',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 57,
    title: 'Vercel',
    logoName: 'vercel',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 41,
    title: 'React.js',
    logoName: 'react',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    modifiedAt: {
      date: '2024-07-14 00:00:00.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    id: 12,
    title: 'Java',
    logoName: 'openjdk',
    url: 'https://www.tutorialspoint.com/java/java_documentation.htm',
    featured: true,
    experiences: {},
    projects: {},
  },
  {
    createdAt: null,
    modifiedAt: null,
    id: 49,
    title: 'Nuxt',
    logoName: 'nuxt',
    url: null,
    featured: true,
    experiences: {},
    projects: {},
  },
] as const;
